#!/bin/bash

scrot /tmp/lockbackground.png
convert /tmp/lockbackground.png -blur 0x5 /tmp/lockbackground.png
composite -gravity center "$SETUP_CONFIGURATIONS"/.i3/lock-screen/overlay /tmp/lockbackground.png /tmp/lockbackground.png
i3lock -i /tmp/lockbackground.png
rm -f   /tmp/lockbackground.png
